const courseData = [
  {
    "id": "33050 01",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Erik G Hurst",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "33050 02",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Erik G Hurst",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.4,
    "clarity": 4.1,
    "interest": 4.4,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "33520 85",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.2,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.1
  },
  {
    "id": "33050 01",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Spring 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "33050 02",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Spring 2024",
    "hoursPerWeek": 4.8,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "33050 81",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Spring 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "33401 01",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2024",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.1
  },
  {
    "id": "33401 02",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2024",
    "hoursPerWeek": 4.8,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "33401 81",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.8,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "33520 01",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Spring 2024",
    "hoursPerWeek": 4.8,
    "clarity": 2.8,
    "interest": 3.4,
    "usefulness": 3.6,
    "overall": 3.0,
    "recommendation": 2.9
  },
  {
    "id": "33520 81",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Spring 2024",
    "hoursPerWeek": 4.3,
    "clarity": 3.6,
    "interest": 3.9,
    "usefulness": 3.6,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "33520 85",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Spring 2024",
    "hoursPerWeek": 3.6,
    "clarity": 3.5,
    "interest": 3.7,
    "usefulness": 3.6,
    "overall": 3.3,
    "recommendation": 3.3
  },
  {
    "id": "33112 01",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 4.1
  },
  {
    "id": "33112 02",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.3,
    "interest": 3.7,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "33112 85",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 4.1
  },
  {
    "id": "33502 01",
    "title": "International Financial Policy",
    "instructor": "Rohan Kekre",
    "term": "Winter 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "33502 02",
    "title": "International Financial Policy",
    "instructor": "Rohan Kekre",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "33502 81",
    "title": "International Financial Policy",
    "instructor": "Rohan Kekre",
    "term": "Winter 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "33050 01",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Elisa Rubbo",
    "term": "Winter 2024",
    "hoursPerWeek": 6.3,
    "clarity": 3.7,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.9,
    "recommendation": 3.6
  },
  {
    "id": "33050 85",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Elisa Rubbo",
    "term": "Winter 2024",
    "hoursPerWeek": 7.7,
    "clarity": 3.0,
    "interest": 2.6,
    "usefulness": 3.6,
    "overall": 3.1,
    "recommendation": 2.8
  },
  {
    "id": "33050 01",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.1
  },
  {
    "id": "33050 02",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Winter 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "33050 81",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Joseph Vavra",
    "term": "Winter 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "33050 85",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Jason Faberman",
    "term": "Winter 2025",
    "hoursPerWeek": 4.5,
    "clarity": 4.1,
    "interest": 3.8,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 3.9
  },
  {
    "id": "33112 01",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2025",
    "hoursPerWeek": 2.7,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 4.0
  },
  {
    "id": "33112 02",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2025",
    "hoursPerWeek": 3.0,
    "clarity": 3.9,
    "interest": 3.6,
    "usefulness": 3.5,
    "overall": 3.4,
    "recommendation": 3.7
  },
  {
    "id": "33112 81",
    "title": "Business in Historical Perspective",
    "instructor": "Richard Hornbeck",
    "term": "Winter 2025",
    "hoursPerWeek": 3.3,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "33401 01",
    "title": "Money and Banking",
    "instructor": "Kilian Huber",
    "term": "Winter 2025",
    "hoursPerWeek": 3.8,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.5
  },
  {
    "id": "33401 02",
    "title": "Money and Banking",
    "instructor": "Kilian Huber",
    "term": "Winter 2025",
    "hoursPerWeek": 2.9,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "33401 81",
    "title": "Money and Banking",
    "instructor": "Kilian Huber",
    "term": "Winter 2025",
    "hoursPerWeek": 3.8,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "33502 01",
    "title": "International Financial Policy",
    "instructor": "Rohan Kekre",
    "term": "Winter 2025",
    "hoursPerWeek": 3.6,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "33502 81",
    "title": "International Financial Policy",
    "instructor": "Rohan Kekre",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "33050 01",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Veronica Guerrieri",
    "term": "Spring 2025",
    "hoursPerWeek": 3.0,
    "clarity": 4.0,
    "interest": 3.4,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "33050 02",
    "title": "Macroeconomics and the Business Environment",
    "instructor": "Veronica Guerrieri",
    "term": "Spring 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.4,
    "interest": 3.9,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 3.6
  },
  {
    "id": "33401 01",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2025",
    "hoursPerWeek": 5.2,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "33401 02",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2025",
    "hoursPerWeek": 5.1,
    "clarity": 3.9,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "33401 81",
    "title": "Money and Banking",
    "instructor": "Randall S Kroszner",
    "term": "Spring 2025",
    "hoursPerWeek": 6.1,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "33501 01",
    "title": "International Commercial Policy",
    "instructor": "Rodrigo Adao",
    "term": "Spring 2025",
    "hoursPerWeek": 4.6,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "33520 01",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Spring 2025",
    "hoursPerWeek": 3.9,
    "clarity": 3.4,
    "interest": 3.8,
    "usefulness": 3.5,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "33520 81",
    "title": "The Wealth of Nations",
    "instructor": "Chang-Tai Hsieh",
    "term": "Spring 2025",
    "hoursPerWeek": 3.1,
    "clarity": 3.9,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.2
  }
];