const courseData = [
  {
    "id": "37000 01",
    "title": "Marketing Strategy",
    "instructor": "Avner Strulov-Shlain",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.0,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.5,
    "recommendation": 3.5
  },
  {
    "id": "37000 02",
    "title": "Marketing Strategy",
    "instructor": "Avner Strulov-Shlain",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "37000 03",
    "title": "Marketing Strategy",
    "instructor": "Avner Strulov-Shlain",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.0,
    "clarity": 3.9,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "37000 04",
    "title": "Marketing Strategy",
    "instructor": "Andreas Kraft",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.3,
    "clarity": 3.7,
    "interest": 3.5,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.2
  },
  {
    "id": "37000 81",
    "title": "Marketing Strategy",
    "instructor": "Andreas Kraft",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "37105 81",
    "title": "Data Science for Marketing Decision Making",
    "instructor": "Giovanni Compiani",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.0,
    "clarity": 4.5,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "37110 01",
    "title": "Marketing Strategy (with Sustainability Simulation)",
    "instructor": "Pradeep Chintagunta",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.8
  },
  {
    "id": "37200 01",
    "title": "New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.0,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "37200 02",
    "title": "New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.0,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "37200 81",
    "title": "New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.9,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "37301 81",
    "title": "Digital Marketing",
    "instructor": "Lil Mohan",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "37000 01",
    "title": "Marketing Strategy",
    "instructor": "Stephanie Smith",
    "term": "Spring 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.6,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "37000 02",
    "title": "Marketing Strategy",
    "instructor": "Stephanie Smith",
    "term": "Spring 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "37000 85",
    "title": "Marketing Strategy",
    "instructor": "Christopher Krohn",
    "term": "Spring 2024",
    "hoursPerWeek": 5.4,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "37101 01",
    "title": "Consumer Behavior",
    "instructor": "Kristin Donnelly",
    "term": "Spring 2024",
    "hoursPerWeek": 2.8,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "37101 85",
    "title": "Consumer Behavior",
    "instructor": "Kristin Donnelly",
    "term": "Spring 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "37103 01",
    "title": "Data-Driven Marketing",
    "instructor": "Guenter Hitsch",
    "term": "Spring 2024",
    "hoursPerWeek": 5.6,
    "clarity": 3.6,
    "interest": 3.1,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "37103 02",
    "title": "Data-Driven Marketing",
    "instructor": "Guenter Hitsch",
    "term": "Spring 2024",
    "hoursPerWeek": 5.8,
    "clarity": 4.8,
    "interest": 4.2,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "37103 81",
    "title": "Data-Driven Marketing",
    "instructor": "Guenter Hitsch",
    "term": "Spring 2024",
    "hoursPerWeek": 5.1,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 5.0,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "37200 85",
    "title": "New Products and Services",
    "instructor": "Craig Terrill",
    "term": "Spring 2024",
    "hoursPerWeek": 5.2,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "37201 01",
    "title": "Lab in Developing New Products and Services",
    "instructor": "Craig Terrill",
    "term": "Spring 2024",
    "hoursPerWeek": 11.4,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "37201 81",
    "title": "Lab in Developing New Products and Services",
    "instructor": "Craig Terrill",
    "term": "Spring 2024",
    "hoursPerWeek": 8.6,
    "clarity": 4.2,
    "interest": 3.7,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "37202 01",
    "title": "Pricing Strategies",
    "instructor": "Jean-Pierre Dube",
    "term": "Spring 2024",
    "hoursPerWeek": 5.5,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "37202 02",
    "title": "Pricing Strategies",
    "instructor": "Jean-Pierre Dube",
    "term": "Spring 2024",
    "hoursPerWeek": 4.9,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "37202 81",
    "title": "Pricing Strategies",
    "instructor": "Jean-Pierre Dube",
    "term": "Spring 2024",
    "hoursPerWeek": 6.6,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "37209 01",
    "title": "Brand Management in a Digital Age",
    "instructor": "Thomas Hafen",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.6
  },
  {
    "id": "37000 81",
    "title": "Marketing Strategy",
    "instructor": "Sanjay Dhar",
    "term": "Summer 2024",
    "hoursPerWeek": 6.7,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "37000 85",
    "title": "Marketing Strategy",
    "instructor": "Sanjay Dhar",
    "term": "Summer 2024",
    "hoursPerWeek": 7.0,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.0
  },
  {
    "id": "37101 81",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Summer 2024",
    "hoursPerWeek": 3.5,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "37209 81",
    "title": "Brand Management in a Digital Age",
    "instructor": "Thomas Hafen",
    "term": "Winter 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "37101 01",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "37101 02",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2024",
    "hoursPerWeek": 3.2,
    "clarity": 4.4,
    "interest": 4.8,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.4
  },
  {
    "id": "37101 81",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "37107 01",
    "title": "Experimental Marketing",
    "instructor": "Oleg Urminsky",
    "term": "Winter 2024",
    "hoursPerWeek": 5.8,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "37107 81",
    "title": "Experimental Marketing",
    "instructor": "Oleg Urminsky",
    "term": "Winter 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.0
  },
  {
    "id": "37201 01",
    "title": "Lab in Developing New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Winter 2024",
    "hoursPerWeek": 7.8,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "37201 81",
    "title": "Lab in Developing New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Winter 2024",
    "hoursPerWeek": 8.8,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "37000 01",
    "title": "Marketing Strategy",
    "instructor": "Avner Strulov-Shlain",
    "term": "Winter 2024",
    "hoursPerWeek": 4.9,
    "clarity": 3.9,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.5,
    "recommendation": 3.5
  },
  {
    "id": "37000 02",
    "title": "Marketing Strategy",
    "instructor": "Andreas Kraft",
    "term": "Winter 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.2,
    "interest": 3.8,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "37000 03",
    "title": "Marketing Strategy",
    "instructor": "Andreas Kraft",
    "term": "Winter 2024",
    "hoursPerWeek": 6.1,
    "clarity": 4.0,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 3.5
  },
  {
    "id": "37000 81",
    "title": "Marketing Strategy",
    "instructor": "Avner Strulov-Shlain",
    "term": "Winter 2024",
    "hoursPerWeek": 4.5,
    "clarity": 4.2,
    "interest": 3.8,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "37000 82",
    "title": "Marketing Strategy",
    "instructor": "Christopher Krohn",
    "term": "Winter 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "37110 01",
    "title": "Marketing Strategy (with Sustainability Simulation)",
    "instructor": "Pradeep Chintagunta",
    "term": "Winter 2024",
    "hoursPerWeek": 4.8,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "37200 81",
    "title": "New Products and Services",
    "instructor": "Arthur Middlebrooks",
    "term": "Winter 2024",
    "hoursPerWeek": 7.0,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "37000 01",
    "title": "Marketing Strategy",
    "instructor": "Beidi Hu",
    "term": "Winter 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.3,
    "interest": 3.8,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.6
  },
  {
    "id": "37000 02",
    "title": "Marketing Strategy",
    "instructor": "Beidi Hu",
    "term": "Winter 2025",
    "hoursPerWeek": 2.7,
    "clarity": 4.0,
    "interest": 3.4,
    "usefulness": 3.4,
    "overall": 3.0,
    "recommendation": 3.3
  },
  {
    "id": "37000 03",
    "title": "Marketing Strategy",
    "instructor": "Christopher Krohn",
    "term": "Winter 2025",
    "hoursPerWeek": 6.0,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.6
  },
  {
    "id": "37000 85",
    "title": "Marketing Strategy",
    "instructor": "Christopher Krohn",
    "term": "Winter 2025",
    "hoursPerWeek": 5.7,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "37101 01",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2025",
    "hoursPerWeek": 2.8,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "37101 02",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2025",
    "hoursPerWeek": 3.0,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "37101 85",
    "title": "Consumer Behavior",
    "instructor": "Daniel Bartels",
    "term": "Winter 2025",
    "hoursPerWeek": 8.7,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "37103 01",
    "title": "Data-Driven Marketing",
    "instructor": "Guenter Hitsch",
    "term": "Winter 2025",
    "hoursPerWeek": 5.9,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.1
  },
  {
    "id": "37103 81",
    "title": "Data-Driven Marketing",
    "instructor": "Guenter Hitsch",
    "term": "Winter 2025",
    "hoursPerWeek": 5.7,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "37209 01",
    "title": "Brand Management in a Digital Age",
    "instructor": "Thomas Hafen",
    "term": "Winter 2025",
    "hoursPerWeek": 2.9,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "37209 85",
    "title": "Brand Management in a Digital Age",
    "instructor": "Thomas Hafen",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "37000 01",
    "title": "Marketing Strategy",
    "instructor": "Berkeley Dietvorst",
    "term": "Spring 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "37000 03",
    "title": "Marketing Strategy",
    "instructor": "Malika Korganbekova",
    "term": "Spring 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "37000 04",
    "title": "Marketing Strategy",
    "instructor": "Berkeley Dietvorst",
    "term": "Spring 2025",
    "hoursPerWeek": 5.3,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "37000 81",
    "title": "Marketing Strategy",
    "instructor": "Berkeley Dietvorst",
    "term": "Spring 2025",
    "hoursPerWeek": 4.9,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "37101 01",
    "title": "Consumer Behavior",
    "instructor": "Kristin Donnelly",
    "term": "Spring 2025",
    "hoursPerWeek": 2.2,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "37101 81",
    "title": "Consumer Behavior",
    "instructor": "Kristin Donnelly",
    "term": "Spring 2025",
    "hoursPerWeek": 2.5,
    "clarity": 4.2,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "37200 01",
    "title": "New Products and Services",
    "instructor": "Craig Terrill",
    "term": "Spring 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.0,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.7
  },
  {
    "id": "37200 85",
    "title": "New Products and Services",
    "instructor": "Craig Terrill",
    "term": "Spring 2025",
    "hoursPerWeek": 4.8,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "37202 01",
    "title": "Pricing Strategies",
    "instructor": "Jean-Pierre Dube",
    "term": "Spring 2025",
    "hoursPerWeek": 5.2,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "37202 81",
    "title": "Pricing Strategies",
    "instructor": "Jean-Pierre Dube",
    "term": "Spring 2025",
    "hoursPerWeek": 9.0,
    "clarity": 4.5,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "37209 81",
    "title": "Brand Management in a Digital Age",
    "instructor": "Thomas Hafen",
    "term": "Spring 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.0
  }
];