const courseData = [
  {
    "id": "31403 85",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.3,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "31403 85",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.3,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "33032 81",
    "title": "Managing the Workplace",
    "instructor": "Stacey Kole",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "38001 01",
    "title": "Managing in Organizations",
    "instructor": "Ann McGill",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "38001 02",
    "title": "Managing in Organizations",
    "instructor": "Ann McGill",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.2,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "38001 81",
    "title": "Managing in Organizations",
    "instructor": "Ann McGill",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.1,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "38003 01",
    "title": "Power and Influence in Organizations",
    "instructor": "A. David Nussbaum",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.3,
    "interest": 3.8,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.8
  },
  {
    "id": "38003 02",
    "title": "Power and Influence in Organizations",
    "instructor": "A. David Nussbaum",
    "term": "Autumn 2024",
    "hoursPerWeek": 2.7,
    "clarity": 4.1,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "38003 81",
    "title": "Power and Influence in Organizations",
    "instructor": "A. David Nussbaum",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.4,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.4
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.4
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Spring 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Spring 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "33032 01",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "33032 02",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "33032 81",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "38001 01",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2024",
    "hoursPerWeek": 4.1,
    "clarity": 4.6,
    "interest": 4.2,
    "usefulness": 3.8,
    "overall": 3.5,
    "recommendation": 3.6
  },
  {
    "id": "38001 02",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2024",
    "hoursPerWeek": 2.5,
    "clarity": 3.8,
    "interest": 3.6,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.4
  },
  {
    "id": "38001 85",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2024",
    "hoursPerWeek": 4.5,
    "clarity": 4.0,
    "interest": 3.9,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "38003 01",
    "title": "Power and Influence in Organizations",
    "instructor": "Emma Levine",
    "term": "Spring 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "38003 02",
    "title": "Power and Influence in Organizations",
    "instructor": "Emma Levine",
    "term": "Spring 2024",
    "hoursPerWeek": 2.9,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "38003 81",
    "title": "Power and Influence in Organizations",
    "instructor": "Emma Levine",
    "term": "Spring 2024",
    "hoursPerWeek": 3.1,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "38122 02",
    "title": "Diversity in Organizations",
    "instructor": "Jane Risen",
    "term": "Spring 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.6,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "38122 85",
    "title": "Diversity in Organizations",
    "instructor": "Jane Risen",
    "term": "Spring 2024",
    "hoursPerWeek": 3.8,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "38001 81",
    "title": "Managing in Organizations",
    "instructor": "Ed O'brien",
    "term": "Summer 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "38001 85",
    "title": "Managing in Organizations",
    "instructor": "Ed O'brien",
    "term": "Summer 2024",
    "hoursPerWeek": 3.3,
    "clarity": 4.9,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Winter 2024",
    "hoursPerWeek": 5.0,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Winter 2024",
    "hoursPerWeek": 5.0,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "38001 01",
    "title": "Managing in Organizations",
    "instructor": "Bernd Wittenbrink",
    "term": "Winter 2024",
    "hoursPerWeek": 2.9,
    "clarity": 3.7,
    "interest": 3.0,
    "usefulness": 3.3,
    "overall": 2.7,
    "recommendation": 2.8
  },
  {
    "id": "38001 02",
    "title": "Managing in Organizations",
    "instructor": "Bernd Wittenbrink",
    "term": "Winter 2024",
    "hoursPerWeek": 3.1,
    "clarity": 3.2,
    "interest": 2.8,
    "usefulness": 3.2,
    "overall": 2.8,
    "recommendation": 2.7
  },
  {
    "id": "38001 81",
    "title": "Managing in Organizations",
    "instructor": "Bernd Wittenbrink",
    "term": "Winter 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "33032 81",
    "title": "Managing the Workplace",
    "instructor": "Stacey Kole",
    "term": "Winter 2024",
    "hoursPerWeek": 4.0,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Winter 2025",
    "hoursPerWeek": 4.2,
    "clarity": 4.1,
    "interest": 3.8,
    "usefulness": 3.8,
    "overall": 3.6,
    "recommendation": 3.3
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Winter 2025",
    "hoursPerWeek": 4.2,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 3.8,
    "overall": 3.6,
    "recommendation": 3.3
  },
  {
    "id": "38001 85",
    "title": "Managing in Organizations",
    "instructor": "Alexander Todorov",
    "term": "Winter 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 3.8,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "38122 01",
    "title": "Diversity in Organizations",
    "instructor": "Jane Risen",
    "term": "Winter 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.8,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.7
  },
  {
    "id": "38122 02",
    "title": "Diversity in Organizations",
    "instructor": "Jane Risen",
    "term": "Winter 2025",
    "hoursPerWeek": 5.0,
    "clarity": 4.5,
    "interest": 4.0,
    "usefulness": 4.5,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "38122 81",
    "title": "Diversity in Organizations",
    "instructor": "Jane Risen",
    "term": "Winter 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.9,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.9
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Spring 2025",
    "hoursPerWeek": 3.0,
    "clarity": 4.7,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.1
  },
  {
    "id": "31403 01",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Spring 2025",
    "hoursPerWeek": 3.0,
    "clarity": 4.7,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.1
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Harry L Davis",
    "term": "Spring 2025",
    "hoursPerWeek": 5.2,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "31403 81",
    "title": "Leadership Studio",
    "instructor": "Nancy Tennant",
    "term": "Spring 2025",
    "hoursPerWeek": 5.2,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "33032 01",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2025",
    "hoursPerWeek": 3.0,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.2
  },
  {
    "id": "33032 02",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2025",
    "hoursPerWeek": 2.7,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "33032 85",
    "title": "Managing the Workplace",
    "instructor": "Canice Prendergast",
    "term": "Spring 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "38001 01",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2025",
    "hoursPerWeek": 3.2,
    "clarity": 3.4,
    "interest": 2.9,
    "usefulness": 2.9,
    "overall": 2.3,
    "recommendation": 2.4
  },
  {
    "id": "38001 02",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2025",
    "hoursPerWeek": 4.5,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "38001 03",
    "title": "Managing in Organizations",
    "instructor": "Ayelet Fishbach",
    "term": "Spring 2025",
    "hoursPerWeek": 2.4,
    "clarity": 2.9,
    "interest": 2.6,
    "usefulness": 2.9,
    "overall": 2.6,
    "recommendation": 2.4
  }
];