const courseData = [
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Autumn 2020",
    "hoursPerWeek": 2.7,
    "clarity": 4.3,
    "interest": 3.6,
    "usefulness": 3.9,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.2,
    "clarity": 4.4,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.3,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Autumn 2020",
    "hoursPerWeek": 6.9,
    "clarity": 4.7,
    "interest": 4.2,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Autumn 2020",
    "hoursPerWeek": 10.5,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Autumn 2020",
    "hoursPerWeek": 10.7,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.1,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.8,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.2,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.7,
    "clarity": 3.9,
    "interest": 3.3,
    "usefulness": 3.6,
    "overall": 3.4,
    "recommendation": 3.3
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.7,
    "clarity": 4.2,
    "interest": 3.5,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 3.6
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2022",
    "hoursPerWeek": 6.8,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.3,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.1
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2022",
    "hoursPerWeek": 6.0,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 3.7,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.8,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.3
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.2,
    "clarity": 3.9,
    "interest": 3.5,
    "usefulness": 3.9,
    "overall": 3.5,
    "recommendation": 3.3
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.6,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Autumn 2023",
    "hoursPerWeek": 2.7,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Autumn 2023",
    "hoursPerWeek": 2.9,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Autumn 2023",
    "hoursPerWeek": 2.9,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.3,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.2,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "36106 03",
    "title": "Managerial Decision Modeling",
    "instructor": "Rad Niazadeh",
    "term": "Autumn 2024",
    "hoursPerWeek": 7.1,
    "clarity": 4.1,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "36106 04",
    "title": "Managerial Decision Modeling",
    "instructor": "Rad Niazadeh",
    "term": "Autumn 2024",
    "hoursPerWeek": 8.3,
    "clarity": 3.9,
    "interest": 4.1,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 3.7
  },
  {
    "id": "36106 05",
    "title": "Managerial Decision Modeling",
    "instructor": "Rad Niazadeh",
    "term": "Autumn 2024",
    "hoursPerWeek": 8.7,
    "clarity": 4.1,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Autumn 2024",
    "hoursPerWeek": 7.8,
    "clarity": 4.1,
    "interest": 3.8,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Autumn 2024",
    "hoursPerWeek": 2.3,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 3.6
  },
  {
    "id": "36109 01",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2021",
    "hoursPerWeek": 4.8,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "36109 81",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2021",
    "hoursPerWeek": 4.9,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.5,
    "recommendation": 4.3
  },
  {
    "id": "36109 85",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2021",
    "hoursPerWeek": 4.1,
    "clarity": 4.8,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.6
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Spring 2021",
    "hoursPerWeek": 6.6,
    "clarity": 4.2,
    "interest": 3.6,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Spring 2021",
    "hoursPerWeek": 6.0,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2021",
    "hoursPerWeek": 2.9,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2021",
    "hoursPerWeek": 2.6,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2021",
    "hoursPerWeek": 2.8,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "36109 01",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2022",
    "hoursPerWeek": 3.4,
    "clarity": 4.8,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.2
  },
  {
    "id": "36109 02",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2022",
    "hoursPerWeek": 4.6,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "36109 81",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2022",
    "hoursPerWeek": 6.4,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Spring 2022",
    "hoursPerWeek": 5.4,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Spring 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.0,
    "interest": 3.7,
    "usefulness": 3.8,
    "overall": 3.3,
    "recommendation": 3.3
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Varun Gupta",
    "term": "Spring 2022",
    "hoursPerWeek": 6.4,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2022",
    "hoursPerWeek": 2.8,
    "clarity": 4.8,
    "interest": 5.0,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2022",
    "hoursPerWeek": 2.3,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.8
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2022",
    "hoursPerWeek": 2.6,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2023",
    "hoursPerWeek": 5.5,
    "clarity": 4.2,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.2
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2023",
    "hoursPerWeek": 5.0,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 3.9
  },
  {
    "id": "36109 01",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2023",
    "hoursPerWeek": 4.9,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.5
  },
  {
    "id": "36109 81",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2023",
    "hoursPerWeek": 5.8,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "36109 85",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2023",
    "hoursPerWeek": 7.3,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.8,
    "recommendation": 4.5
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2023",
    "hoursPerWeek": 2.5,
    "clarity": 4.9,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2023",
    "hoursPerWeek": 2.7,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.6
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Anuj Shah",
    "term": "Spring 2023",
    "hoursPerWeek": 3.0,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.9
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2024",
    "hoursPerWeek": 6.1,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2024",
    "hoursPerWeek": 5.4,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "36109 01",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2024",
    "hoursPerWeek": 5.8,
    "clarity": 4.2,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "36109 02",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2024",
    "hoursPerWeek": 5.2,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "36109 81",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Spring 2024",
    "hoursPerWeek": 3.5,
    "clarity": 3.8,
    "interest": 3.0,
    "usefulness": 3.6,
    "overall": 3.3,
    "recommendation": 3.1
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Spring 2024",
    "hoursPerWeek": 3.1,
    "clarity": 3.6,
    "interest": 2.7,
    "usefulness": 3.2,
    "overall": 2.9,
    "recommendation": 2.5
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Spring 2024",
    "hoursPerWeek": 3.0,
    "clarity": 3.9,
    "interest": 2.9,
    "usefulness": 3.7,
    "overall": 3.4,
    "recommendation": 3.1
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Summer 2020",
    "hoursPerWeek": 3.7,
    "clarity": 3.9,
    "interest": 3.4,
    "usefulness": 3.8,
    "overall": 3.3,
    "recommendation": 3.4
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Summer 2020",
    "hoursPerWeek": 3.8,
    "clarity": 3.8,
    "interest": 3.8,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Summer 2020",
    "hoursPerWeek": 9.0,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Summer 2023",
    "hoursPerWeek": 4.1,
    "clarity": 3.6,
    "interest": 2.8,
    "usefulness": 3.5,
    "overall": 3.1,
    "recommendation": 3.1
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Summer 2023",
    "hoursPerWeek": 4.8,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 3.9
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "John Vande Vate",
    "term": "Summer 2024",
    "hoursPerWeek": 7.4,
    "clarity": 3.3,
    "interest": 3.2,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 2.9
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Winter 2021",
    "hoursPerWeek": 4.9,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Winter 2021",
    "hoursPerWeek": 4.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Baris Ata",
    "term": "Winter 2021",
    "hoursPerWeek": 5.7,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 4.8,
    "recommendation": 5.0
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2021",
    "hoursPerWeek": 3.8,
    "clarity": 3.2,
    "interest": 2.3,
    "usefulness": 3.5,
    "overall": 2.9,
    "recommendation": 2.9
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2021",
    "hoursPerWeek": 4.6,
    "clarity": 4.1,
    "interest": 3.7,
    "usefulness": 4.3,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.1,
    "interest": 3.6,
    "usefulness": 4.0,
    "overall": 3.5,
    "recommendation": 3.4
  },
  {
    "id": "38120 01",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2021",
    "hoursPerWeek": 2.4,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "38120 81",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2021",
    "hoursPerWeek": 2.9,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.6
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Winter 2022",
    "hoursPerWeek": 2.7,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 3.9,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Winter 2022",
    "hoursPerWeek": 2.0,
    "clarity": 3.4,
    "interest": 2.8,
    "usefulness": 3.3,
    "overall": 2.8,
    "recommendation": 2.8
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Kaiyuan Chris Hsee",
    "term": "Winter 2022",
    "hoursPerWeek": 2.5,
    "clarity": 3.7,
    "interest": 3.2,
    "usefulness": 3.9,
    "overall": 3.3,
    "recommendation": 3.2
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Otis Jennings",
    "term": "Winter 2022",
    "hoursPerWeek": 5.9,
    "clarity": 3.5,
    "interest": 3.9,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "38120 01",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2022",
    "hoursPerWeek": 2.3,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.9
  },
  {
    "id": "38120 85",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2022",
    "hoursPerWeek": 2.7,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2022",
    "hoursPerWeek": 5.4,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2022",
    "hoursPerWeek": 6.3,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2022",
    "hoursPerWeek": 6.0,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2023",
    "hoursPerWeek": 3.0,
    "clarity": 3.6,
    "interest": 2.9,
    "usefulness": 3.6,
    "overall": 3.0,
    "recommendation": 2.9
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2023",
    "hoursPerWeek": 3.2,
    "clarity": 4.2,
    "interest": 2.8,
    "usefulness": 3.6,
    "overall": 3.0,
    "recommendation": 3.0
  },
  {
    "id": "38002 85",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Winter 2023",
    "hoursPerWeek": 4.7,
    "clarity": 4.1,
    "interest": 3.5,
    "usefulness": 4.3,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "38120 01",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2023",
    "hoursPerWeek": 2.3,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "38120 81",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2023",
    "hoursPerWeek": 2.5,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2023",
    "hoursPerWeek": 6.8,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2023",
    "hoursPerWeek": 7.2,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2023",
    "hoursPerWeek": 6.8,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2024",
    "hoursPerWeek": 6.1,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.3,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2024",
    "hoursPerWeek": 7.9,
    "clarity": 4.0,
    "interest": 3.7,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.6
  },
  {
    "id": "36106 85",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2024",
    "hoursPerWeek": 8.4,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.1
  },
  {
    "id": "38120 01",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2024",
    "hoursPerWeek": 2.5,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "38120 02",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2024",
    "hoursPerWeek": 2.7,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.9
  },
  {
    "id": "38120 85",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2024",
    "hoursPerWeek": 2.8,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "30005 01",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Anna Costello",
    "term": "Winter 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "30005 02",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Anna Costello",
    "term": "Winter 2025",
    "hoursPerWeek": 3.9,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.6
  },
  {
    "id": "30005 81",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Anna Costello",
    "term": "Winter 2025",
    "hoursPerWeek": 4.6,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2025",
    "hoursPerWeek": 6.8,
    "clarity": 3.8,
    "interest": 3.8,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2025",
    "hoursPerWeek": 7.6,
    "clarity": 3.9,
    "interest": 3.3,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 3.4
  },
  {
    "id": "36106 81",
    "title": "Managerial Decision Modeling",
    "instructor": "Burhaneddin Sandikci",
    "term": "Winter 2025",
    "hoursPerWeek": 9.4,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Saurabh Bhargava",
    "term": "Winter 2025",
    "hoursPerWeek": 2.0,
    "clarity": 2.9,
    "interest": 2.7,
    "usefulness": 2.5,
    "overall": 2.3,
    "recommendation": 2.3
  },
  {
    "id": "38002 02",
    "title": "Managerial Decision Making",
    "instructor": "Saurabh Bhargava",
    "term": "Winter 2025",
    "hoursPerWeek": 2.1,
    "clarity": 3.5,
    "interest": 4.0,
    "usefulness": 3.6,
    "overall": 3.3,
    "recommendation": 3.5
  },
  {
    "id": "38120 01",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2025",
    "hoursPerWeek": 2.3,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "38120 02",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2025",
    "hoursPerWeek": 2.6,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.9
  },
  {
    "id": "38120 81",
    "title": "The Study of Behavioral Economics",
    "instructor": "Devin Pope",
    "term": "Winter 2025",
    "hoursPerWeek": 2.4,
    "clarity": 4.9,
    "interest": 5.0,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "30005 01",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Christopher Stewart",
    "term": "Spring 2025",
    "hoursPerWeek": 4.5,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "30005 02",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Christopher Stewart",
    "term": "Spring 2025",
    "hoursPerWeek": 4.8,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "30005 85",
    "title": "Internal Information for Strategic Decisions",
    "instructor": "Christopher Stewart",
    "term": "Spring 2025",
    "hoursPerWeek": 4.8,
    "clarity": 4.5,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "36106 01",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2025",
    "hoursPerWeek": 4.8,
    "clarity": 4.8,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.5
  },
  {
    "id": "36106 02",
    "title": "Managerial Decision Modeling",
    "instructor": "Philipp Afeche",
    "term": "Spring 2025",
    "hoursPerWeek": 5.4,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "36109 01",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2025",
    "hoursPerWeek": 5.4,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "36109 02",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "36109 81",
    "title": "Advanced Decision Models with Python",
    "instructor": "Donald D Eisenstein",
    "term": "Spring 2025",
    "hoursPerWeek": 4.9,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "38002 01",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Spring 2025",
    "hoursPerWeek": 3.1,
    "clarity": 3.6,
    "interest": 3.6,
    "usefulness": 4.1,
    "overall": 3.3,
    "recommendation": 3.1
  },
  {
    "id": "38002 81",
    "title": "Managerial Decision Making",
    "instructor": "Reid Hastie",
    "term": "Spring 2025",
    "hoursPerWeek": 2.6,
    "clarity": 3.1,
    "interest": 3.0,
    "usefulness": 3.4,
    "overall": 2.7,
    "recommendation": 2.7
  }
];