const courseData = [
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2020",
    "hoursPerWeek": 5.7,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "G M Constantinides",
    "term": "Autumn 2020",
    "hoursPerWeek": 12.9,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Douglas W Diamond",
    "term": "Autumn 2020",
    "hoursPerWeek": 13.6,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.3
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Zhiguo He",
    "term": "Autumn 2020",
    "hoursPerWeek": 13.6,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.3
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "John Heaton",
    "term": "Autumn 2020",
    "hoursPerWeek": 12.9,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2020",
    "hoursPerWeek": 8.0,
    "clarity": 4.0,
    "interest": 3.5,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2020",
    "hoursPerWeek": 6.1,
    "clarity": 3.5,
    "interest": 3.1,
    "usefulness": 3.7,
    "overall": 3.2,
    "recommendation": 3.2
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2020",
    "hoursPerWeek": 6.6,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2020",
    "hoursPerWeek": 5.4,
    "clarity": 4.2,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2020",
    "hoursPerWeek": 6.3,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2020",
    "hoursPerWeek": 7.7,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.7
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Scott Nelson",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.5,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Scott Nelson",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.9,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Scott Nelson",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.6,
    "clarity": 4.7,
    "interest": 4.3,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.2,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "35201 02",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.1,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.7,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.9,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.1,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "G M Constantinides",
    "term": "Autumn 2021",
    "hoursPerWeek": 21.2,
    "clarity": 4.0,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Douglas W Diamond",
    "term": "Autumn 2021",
    "hoursPerWeek": 17.7,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.3
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Zhiguo He",
    "term": "Autumn 2021",
    "hoursPerWeek": 17.7,
    "clarity": 4.0,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.3
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "John Heaton",
    "term": "Autumn 2021",
    "hoursPerWeek": 21.2,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2021",
    "hoursPerWeek": 7.4,
    "clarity": 4.0,
    "interest": 3.8,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.7,
    "clarity": 3.5,
    "interest": 3.3,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.1
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Autumn 2021",
    "hoursPerWeek": 6.2,
    "clarity": 3.4,
    "interest": 3.6,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.6
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2021",
    "hoursPerWeek": 6.0,
    "clarity": 4.3,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2021",
    "hoursPerWeek": 7.0,
    "clarity": 4.2,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2021",
    "hoursPerWeek": 7.6,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Ayan Bhattacharya",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.9,
    "clarity": 4.0,
    "interest": 3.7,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Ayan Bhattacharya",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.8,
    "clarity": 3.4,
    "interest": 3.2,
    "usefulness": 3.5,
    "overall": 3.2,
    "recommendation": 3.3
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Ayan Bhattacharya",
    "term": "Autumn 2022",
    "hoursPerWeek": 9.0,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.5,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.3,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Douglas W Diamond",
    "term": "Autumn 2022",
    "hoursPerWeek": 14.4,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "34903 50",
    "title": "Corporate Finance I",
    "instructor": "Zhiguo He",
    "term": "Autumn 2022",
    "hoursPerWeek": 14.4,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2022",
    "hoursPerWeek": 6.0,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2022",
    "hoursPerWeek": 7.7,
    "clarity": 4.6,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.6,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2023",
    "hoursPerWeek": 7.7,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "James Fasano",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.5,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.7,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.8,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Victor Lyonnet",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.8,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Victor Lyonnet",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.2,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.5,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Victor Lyonnet",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.5,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.2,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.2,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 4.9
  },
  {
    "id": "35210 01",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.7,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35210 81",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.2,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2024",
    "hoursPerWeek": 7.1,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Steven Neil Kaplan",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.7,
    "clarity": 4.2,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "James Fasano",
    "term": "Autumn 2024",
    "hoursPerWeek": 7.9,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "Lars P Hansen",
    "term": "Autumn 2024",
    "hoursPerWeek": 15.0,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 5.0,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "34901 50",
    "title": "Asset Pricing I",
    "instructor": "John Heaton",
    "term": "Autumn 2024",
    "hoursPerWeek": 15.0,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 5.0,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Anthony Zhang",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.1,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.7
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Anthony Zhang",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35000 03",
    "title": "Investments",
    "instructor": "Ian Dew-Becker",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.1,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "35000 04",
    "title": "Investments",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.6,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "35000 05",
    "title": "Investments",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.1,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Bruce Carlin",
    "term": "Autumn 2024",
    "hoursPerWeek": 5.3,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "35050 50",
    "title": "Asset Pricing I",
    "instructor": "Lars P Hansen",
    "term": "Autumn 2024",
    "hoursPerWeek": 18.6,
    "clarity": 3.6,
    "interest": 3.6,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "35050 50",
    "title": "Asset Pricing I",
    "instructor": "John Heaton",
    "term": "Autumn 2024",
    "hoursPerWeek": 18.6,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "35070 50",
    "title": "Corporate Finance I",
    "instructor": "Douglas W Diamond",
    "term": "Autumn 2024",
    "hoursPerWeek": 17.5,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 5.0
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Andres Sarto",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.2,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Andres Sarto",
    "term": "Autumn 2024",
    "hoursPerWeek": 2.9,
    "clarity": 4.0,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Andres Sarto",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.7,
    "clarity": 3.9,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.4,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.5,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2021",
    "hoursPerWeek": 4.2,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2021",
    "hoursPerWeek": 4.3,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "35130 81",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2021",
    "hoursPerWeek": 9.5,
    "clarity": 3.8,
    "interest": 3.5,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Jessica Jeffers",
    "term": "Spring 2021",
    "hoursPerWeek": 4.4,
    "clarity": 3.6,
    "interest": 3.4,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.4
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Jessica Jeffers",
    "term": "Spring 2021",
    "hoursPerWeek": 4.8,
    "clarity": 3.8,
    "interest": 3.5,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.5
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Jessica Jeffers",
    "term": "Spring 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Mark Mitchell",
    "term": "Spring 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35120 01",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2021",
    "hoursPerWeek": 6.3,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "35120 02",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2021",
    "hoursPerWeek": 5.9,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "35120 81",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2021",
    "hoursPerWeek": 7.0,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2021",
    "hoursPerWeek": 4.2,
    "clarity": 3.9,
    "interest": 3.1,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.9
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2021",
    "hoursPerWeek": 5.6,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Vincent Bogousslavsky",
    "term": "Spring 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Vincent Bogousslavsky",
    "term": "Spring 2022",
    "hoursPerWeek": 4.1,
    "clarity": 4.5,
    "interest": 4.1,
    "usefulness": 3.9,
    "overall": 3.8,
    "recommendation": 3.7
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Vincent Bogousslavsky",
    "term": "Spring 2022",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 3.9,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Olivier Darmouni",
    "term": "Spring 2022",
    "hoursPerWeek": 3.0,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 3.8,
    "overall": 3.2,
    "recommendation": 3.3
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Olivier Darmouni",
    "term": "Spring 2022",
    "hoursPerWeek": 3.2,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Olivier Darmouni",
    "term": "Spring 2022",
    "hoursPerWeek": 3.9,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "35130 81",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2022",
    "hoursPerWeek": 7.7,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Mark Mitchell",
    "term": "Spring 2022",
    "hoursPerWeek": 5.4,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35120 01",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2022",
    "hoursPerWeek": 5.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "35120 81",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2022",
    "hoursPerWeek": 6.4,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35120 85",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2022",
    "hoursPerWeek": 6.0,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 4.8
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2022",
    "hoursPerWeek": 4.6,
    "clarity": 4.1,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.2
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2022",
    "hoursPerWeek": 5.1,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.2,
    "recommendation": 4.5
  },
  {
    "id": "35130 81",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2023",
    "hoursPerWeek": 10.5,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Mark Mitchell",
    "term": "Spring 2023",
    "hoursPerWeek": 5.8,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2023",
    "hoursPerWeek": 4.3,
    "clarity": 4.3,
    "interest": 3.9,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2023",
    "hoursPerWeek": 8.6,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35120 01",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2023",
    "hoursPerWeek": 5.9,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "35120 02",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2023",
    "hoursPerWeek": 6.1,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35120 81",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2023",
    "hoursPerWeek": 6.5,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Spring 2023",
    "hoursPerWeek": 5.0,
    "clarity": 3.5,
    "interest": 3.4,
    "usefulness": 3.7,
    "overall": 3.2,
    "recommendation": 3.0
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Spring 2023",
    "hoursPerWeek": 3.9,
    "clarity": 3.7,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.4,
    "recommendation": 3.3
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Spring 2023",
    "hoursPerWeek": 6.0,
    "clarity": 3.8,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.7
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2023",
    "hoursPerWeek": 4.4,
    "clarity": 3.9,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2023",
    "hoursPerWeek": 5.2,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Spring 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 3.8,
    "usefulness": 4.2,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Spring 2024",
    "hoursPerWeek": 5.1,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Spring 2024",
    "hoursPerWeek": 4.8,
    "clarity": 3.9,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Spring 2024",
    "hoursPerWeek": 5.5,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "35120 01",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2024",
    "hoursPerWeek": 5.8,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35120 02",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2024",
    "hoursPerWeek": 5.1,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.6
  },
  {
    "id": "35120 85",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2024",
    "hoursPerWeek": 5.3,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "35130 81",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2024",
    "hoursPerWeek": 10.8,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.6,
    "overall": 4.1,
    "recommendation": 3.6
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.6,
    "interest": 4.0,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.1
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Spring 2024",
    "hoursPerWeek": 5.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Spring 2024",
    "hoursPerWeek": 5.7,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Charles Hadlock",
    "term": "Summer 2020",
    "hoursPerWeek": 6.9,
    "clarity": 4.0,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Charles Hadlock",
    "term": "Summer 2020",
    "hoursPerWeek": 6.5,
    "clarity": 4.2,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35201 85",
    "title": "Cases in Financial Management",
    "instructor": "Charles Hadlock",
    "term": "Summer 2020",
    "hoursPerWeek": 7.0,
    "clarity": 4.5,
    "interest": 4.8,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2020",
    "hoursPerWeek": 4.2,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2020",
    "hoursPerWeek": 3.8,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Summer 2020",
    "hoursPerWeek": 9.5,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.9,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "35000 82",
    "title": "Investments",
    "instructor": "Pietro Veronesi",
    "term": "Summer 2020",
    "hoursPerWeek": 7.6,
    "clarity": 3.7,
    "interest": 3.6,
    "usefulness": 3.9,
    "overall": 3.4,
    "recommendation": 3.4
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Alexander Chinco",
    "term": "Summer 2021",
    "hoursPerWeek": 3.2,
    "clarity": 3.3,
    "interest": 3.5,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.4
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Alexander Chinco",
    "term": "Summer 2021",
    "hoursPerWeek": 3.8,
    "clarity": 3.6,
    "interest": 3.7,
    "usefulness": 4.2,
    "overall": 3.6,
    "recommendation": 3.9
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Charles Hadlock",
    "term": "Summer 2021",
    "hoursPerWeek": 5.0,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "35201 85",
    "title": "Cases in Financial Management",
    "instructor": "Charles Hadlock",
    "term": "Summer 2021",
    "hoursPerWeek": 5.9,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.8
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Summer 2021",
    "hoursPerWeek": 9.0,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Summer 2021",
    "hoursPerWeek": 5.0,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "35201 85",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Summer 2021",
    "hoursPerWeek": 5.9,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.9,
    "recommendation": 4.8
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Theo Vermaelen",
    "term": "Summer 2021",
    "hoursPerWeek": 4.2,
    "clarity": 3.9,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Theo Vermaelen",
    "term": "Summer 2021",
    "hoursPerWeek": 4.4,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Charles Hadlock",
    "term": "Summer 2022",
    "hoursPerWeek": 6.1,
    "clarity": 4.1,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Charles Hadlock",
    "term": "Summer 2022",
    "hoursPerWeek": 5.7,
    "clarity": 4.0,
    "interest": 4.3,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2022",
    "hoursPerWeek": 5.7,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2022",
    "hoursPerWeek": 4.9,
    "clarity": 4.3,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Summer 2022",
    "hoursPerWeek": 9.4,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35201 85",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Summer 2022",
    "hoursPerWeek": 9.7,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.6
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Summer 2023",
    "hoursPerWeek": 9.8,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Joshua Pierce",
    "term": "Summer 2023",
    "hoursPerWeek": 5.6,
    "clarity": 4.2,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 3.9
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Joshua Pierce",
    "term": "Summer 2023",
    "hoursPerWeek": 5.5,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Theo Vermaelen",
    "term": "Summer 2023",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Summer 2024",
    "hoursPerWeek": 9.9,
    "clarity": 4.2,
    "interest": 4.6,
    "usefulness": 4.9,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Pietro Veronesi",
    "term": "Summer 2024",
    "hoursPerWeek": 6.5,
    "clarity": 3.8,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Pietro Veronesi",
    "term": "Summer 2024",
    "hoursPerWeek": 6.0,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.4
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.2,
    "interest": 4.6,
    "usefulness": 4.2,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Anthony Marciano",
    "term": "Summer 2024",
    "hoursPerWeek": 3.8,
    "clarity": 4.3,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.2,
    "recommendation": 4.5
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Winter 2021",
    "hoursPerWeek": 5.7,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.8
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Winter 2021",
    "hoursPerWeek": 6.2,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Alexander Chinco",
    "term": "Winter 2021",
    "hoursPerWeek": 2.8,
    "clarity": 3.4,
    "interest": 3.0,
    "usefulness": 3.4,
    "overall": 2.9,
    "recommendation": 3.0
  },
  {
    "id": "35000 82",
    "title": "Investments",
    "instructor": "Alexander Chinco",
    "term": "Winter 2021",
    "hoursPerWeek": 3.2,
    "clarity": 3.5,
    "interest": 3.4,
    "usefulness": 3.9,
    "overall": 3.2,
    "recommendation": 3.3
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Elisabeth Kempf",
    "term": "Winter 2021",
    "hoursPerWeek": 4.8,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Elisabeth Kempf",
    "term": "Winter 2021",
    "hoursPerWeek": 4.7,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Elisabeth Kempf",
    "term": "Winter 2021",
    "hoursPerWeek": 5.1,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "34902 50",
    "title": "Asset Pricing II",
    "instructor": "Ralph Koijen",
    "term": "Winter 2021",
    "hoursPerWeek": 12.9,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2021",
    "hoursPerWeek": 9.0,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2021",
    "hoursPerWeek": 10.2,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "34902 50",
    "title": "Asset Pricing II",
    "instructor": "Stefan Nagel",
    "term": "Winter 2021",
    "hoursPerWeek": 12.9,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "35200 03",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Winter 2021",
    "hoursPerWeek": 4.9,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "35200 04",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Winter 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.7,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Winter 2021",
    "hoursPerWeek": 5.3,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35210 01",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2021",
    "hoursPerWeek": 6.1,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35210 02",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2021",
    "hoursPerWeek": 6.0,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "35210 81",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2021",
    "hoursPerWeek": 6.6,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "34904 50",
    "title": "Corporate Finance II",
    "instructor": "Amir Sufi",
    "term": "Winter 2021",
    "hoursPerWeek": 14.4,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.6
  },
  {
    "id": "35214 01",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2021",
    "hoursPerWeek": 4.6,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "35214 81",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2021",
    "hoursPerWeek": 5.0,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2021",
    "hoursPerWeek": 4.7,
    "clarity": 3.9,
    "interest": 3.7,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.7
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2021",
    "hoursPerWeek": 5.4,
    "clarity": 3.9,
    "interest": 3.8,
    "usefulness": 4.2,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2021",
    "hoursPerWeek": 7.4,
    "clarity": 3.8,
    "interest": 3.6,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "35000 03",
    "title": "Investments",
    "instructor": "Markus Baldauf",
    "term": "Winter 2022",
    "hoursPerWeek": 4.3,
    "clarity": 3.9,
    "interest": 3.8,
    "usefulness": 3.9,
    "overall": 3.5,
    "recommendation": 3.7
  },
  {
    "id": "35000 82",
    "title": "Investments",
    "instructor": "Markus Baldauf",
    "term": "Winter 2022",
    "hoursPerWeek": 5.9,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Markus Baldauf",
    "term": "Winter 2022",
    "hoursPerWeek": 5.1,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Winter 2022",
    "hoursPerWeek": 5.9,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Jessica Jeffers",
    "term": "Winter 2022",
    "hoursPerWeek": 2.8,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Jessica Jeffers",
    "term": "Winter 2022",
    "hoursPerWeek": 4.3,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Yueran Ma",
    "term": "Winter 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2022",
    "hoursPerWeek": 8.3,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2022",
    "hoursPerWeek": 9.2,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35210 01",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35210 81",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2022",
    "hoursPerWeek": 7.3,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35210 85",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2022",
    "hoursPerWeek": 6.8,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "35214 01",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2022",
    "hoursPerWeek": 3.5,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35214 81",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2022",
    "hoursPerWeek": 4.8,
    "clarity": 4.1,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2022",
    "hoursPerWeek": 4.5,
    "clarity": 3.8,
    "interest": 3.7,
    "usefulness": 3.7,
    "overall": 3.4,
    "recommendation": 3.2
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2022",
    "hoursPerWeek": 6.8,
    "clarity": 3.8,
    "interest": 3.8,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Maria Bastianello",
    "term": "Winter 2023",
    "hoursPerWeek": 3.8,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Maria Bastianello",
    "term": "Winter 2023",
    "hoursPerWeek": 4.9,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Winter 2023",
    "hoursPerWeek": 5.8,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Winter 2023",
    "hoursPerWeek": 4.6,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Winter 2023",
    "hoursPerWeek": 5.4,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "35000 03",
    "title": "Investments",
    "instructor": "John Heaton",
    "term": "Winter 2023",
    "hoursPerWeek": 4.3,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2023",
    "hoursPerWeek": 5.3,
    "clarity": 3.5,
    "interest": 3.4,
    "usefulness": 4.1,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "35200 81",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2023",
    "hoursPerWeek": 7.3,
    "clarity": 3.4,
    "interest": 3.7,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.5
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2023",
    "hoursPerWeek": 7.3,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2023",
    "hoursPerWeek": 8.1,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35150 01",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2023",
    "hoursPerWeek": 8.2,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 3.8,
    "overall": 3.8,
    "recommendation": 3.3
  },
  {
    "id": "35150 81",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2023",
    "hoursPerWeek": 6.1,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "35210 01",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2023",
    "hoursPerWeek": 7.8,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35210 02",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2023",
    "hoursPerWeek": 5.6,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.8
  },
  {
    "id": "35210 81",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2023",
    "hoursPerWeek": 7.2,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "34904 50",
    "title": "Corporate Finance II",
    "instructor": "Amir Sufi",
    "term": "Winter 2023",
    "hoursPerWeek": 12.4,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 5.0
  },
  {
    "id": "35214 01",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2023",
    "hoursPerWeek": 4.3,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "35214 85",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2023",
    "hoursPerWeek": 4.2,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "35150 01",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2024",
    "hoursPerWeek": 7.3,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "35150 85",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2024",
    "hoursPerWeek": 5.6,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2024",
    "hoursPerWeek": 6.7,
    "clarity": 3.2,
    "interest": 3.3,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.0
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2024",
    "hoursPerWeek": 9.9,
    "clarity": 2.8,
    "interest": 3.3,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2024",
    "hoursPerWeek": 7.8,
    "clarity": 3.2,
    "interest": 3.5,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "35214 01",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35214 81",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Winter 2024",
    "hoursPerWeek": 4.0,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2024",
    "hoursPerWeek": 7.9,
    "clarity": 4.3,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2024",
    "hoursPerWeek": 11.3,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Ian Dew-Becker",
    "term": "Winter 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Ian Dew-Becker",
    "term": "Winter 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Ian Dew-Becker",
    "term": "Winter 2024",
    "hoursPerWeek": 4.1,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2025",
    "hoursPerWeek": 7.5,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "34101 81",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Eric Zwick",
    "term": "Winter 2025",
    "hoursPerWeek": 6.7,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "34101 85",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Winter 2025",
    "hoursPerWeek": 11.5,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "34902 50",
    "title": "Asset Pricing II",
    "instructor": "Ralph Koijen",
    "term": "Winter 2025",
    "hoursPerWeek": 11.0,
    "clarity": 4.5,
    "interest": 5.0,
    "usefulness": 4.5,
    "overall": 4.0,
    "recommendation": 4.5
  },
  {
    "id": "34902 50",
    "title": "Asset Pricing II",
    "instructor": "Stefan Nagel",
    "term": "Winter 2025",
    "hoursPerWeek": 11.0,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.5,
    "overall": 4.0,
    "recommendation": 4.5
  },
  {
    "id": "34904 50",
    "title": "Corporate Finance II",
    "instructor": "Amir Sufi",
    "term": "Winter 2025",
    "hoursPerWeek": 10.0,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 5.0
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2025",
    "hoursPerWeek": 4.6,
    "clarity": 3.7,
    "interest": 3.6,
    "usefulness": 3.6,
    "overall": 3.3,
    "recommendation": 3.4
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2025",
    "hoursPerWeek": 4.2,
    "clarity": 3.3,
    "interest": 3.2,
    "usefulness": 3.4,
    "overall": 3.0,
    "recommendation": 3.1
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Michael Weber",
    "term": "Winter 2025",
    "hoursPerWeek": 5.4,
    "clarity": 3.5,
    "interest": 3.4,
    "usefulness": 3.8,
    "overall": 3.3,
    "recommendation": 3.6
  },
  {
    "id": "35150 01",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2025",
    "hoursPerWeek": 4.8,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "35150 81",
    "title": "Advanced Investments",
    "instructor": "Stefan Nagel",
    "term": "Winter 2025",
    "hoursPerWeek": 6.2,
    "clarity": 4.8,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.0
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Winter 2025",
    "hoursPerWeek": 4.0,
    "clarity": 5.0,
    "interest": 4.9,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 4.9
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Winter 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.8,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "35200 03",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2025",
    "hoursPerWeek": 10.4,
    "clarity": 3.4,
    "interest": 3.7,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.1
  },
  {
    "id": "35200 04",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2025",
    "hoursPerWeek": 9.6,
    "clarity": 3.4,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "35200 85",
    "title": "Corporation Finance",
    "instructor": "Anil K Kashyap",
    "term": "Winter 2025",
    "hoursPerWeek": 7.2,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.2
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Winter 2025",
    "hoursPerWeek": 5.6,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "35210 01",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2025",
    "hoursPerWeek": 5.6,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35210 02",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2025",
    "hoursPerWeek": 4.9,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35210 85",
    "title": "International Corporate Finance",
    "instructor": "Raghuram G Rajan",
    "term": "Winter 2025",
    "hoursPerWeek": 5.9,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.6
  },
  {
    "id": "35060 50",
    "title": "Asset Pricing II",
    "instructor": "Ralph Koijen",
    "term": "Winter 2025",
    "hoursPerWeek": 13.3,
    "clarity": 5.0,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.0
  },
  {
    "id": "35060 50",
    "title": "Asset Pricing II",
    "instructor": "Stefan Nagel",
    "term": "Winter 2025",
    "hoursPerWeek": 13.3,
    "clarity": 5.0,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.7,
    "recommendation": 4.0
  },
  {
    "id": "35080 50",
    "title": "Corporate Finance II",
    "instructor": "Amir Sufi",
    "term": "Winter 2025",
    "hoursPerWeek": 12.7,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 5.0,
    "recommendation": 5.0
  },
  {
    "id": "34101 01",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "Scott F Meadow",
    "term": "Spring 2025",
    "hoursPerWeek": 7.5,
    "clarity": 4.6,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "34101 02",
    "title": "Entrepreneurial Finance and Private Equity",
    "instructor": "James Fasano",
    "term": "Spring 2025",
    "hoursPerWeek": 8.4,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "35000 01",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2025",
    "hoursPerWeek": 4.9,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35000 02",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "35000 03",
    "title": "Investments",
    "instructor": "Quentin Vandeweyer",
    "term": "Spring 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "35000 04",
    "title": "Investments",
    "instructor": "Quentin Vandeweyer",
    "term": "Spring 2025",
    "hoursPerWeek": 6.1,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "35000 81",
    "title": "Investments",
    "instructor": "Quentin Vandeweyer",
    "term": "Spring 2025",
    "hoursPerWeek": 5.8,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "35000 85",
    "title": "Investments",
    "instructor": "Niels Gormsen",
    "term": "Spring 2025",
    "hoursPerWeek": 6.7,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35120 01",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2025",
    "hoursPerWeek": 5.7,
    "clarity": 4.8,
    "interest": 5.0,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "35120 02",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2025",
    "hoursPerWeek": 4.7,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "35120 81",
    "title": "Portfolio Management",
    "instructor": "Lubos Pastor",
    "term": "Spring 2025",
    "hoursPerWeek": 6.1,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "35130 01",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2025",
    "hoursPerWeek": 10.1,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.4,
    "overall": 4.5,
    "recommendation": 4.0
  },
  {
    "id": "35130 85",
    "title": "Fixed Income Asset Pricing",
    "instructor": "John Heaton",
    "term": "Spring 2025",
    "hoursPerWeek": 14.7,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.9,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "35200 01",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2025",
    "hoursPerWeek": 4.0,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "35200 02",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.8,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "35200 03",
    "title": "Corporation Finance",
    "instructor": "Pascal Noel",
    "term": "Spring 2025",
    "hoursPerWeek": 4.7,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.6
  },
  {
    "id": "35201 01",
    "title": "Cases in Financial Management",
    "instructor": "Laura Born",
    "term": "Spring 2025",
    "hoursPerWeek": 5.4,
    "clarity": 4.9,
    "interest": 5.0,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "35201 02",
    "title": "Cases in Financial Management",
    "instructor": "Gregor Masini Andrade",
    "term": "Spring 2025",
    "hoursPerWeek": 6.2,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "35201 81",
    "title": "Cases in Financial Management",
    "instructor": "Joshua Pierce",
    "term": "Spring 2025",
    "hoursPerWeek": 4.5,
    "clarity": 4.6,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "35214 01",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Spring 2025",
    "hoursPerWeek": 3.9,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "35214 81",
    "title": "Debt, Distress, and Restructuring",
    "instructor": "Amir Sufi",
    "term": "Spring 2025",
    "hoursPerWeek": 5.1,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.8
  }
];