const courseData = [
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.2,
    "clarity": 4.2,
    "interest": 3.8,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.3,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.0,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.4,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.1,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2022",
    "hoursPerWeek": 5.4,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2022",
    "hoursPerWeek": 2.8,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.5,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.1,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2023",
    "hoursPerWeek": 6.8,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.2,
    "clarity": 3.8,
    "interest": 3.8,
    "usefulness": 4.0,
    "overall": 3.5,
    "recommendation": 3.6
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.0,
    "clarity": 4.3,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Rene Caldentey",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.7,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "40108 85",
    "title": "Revenue Management",
    "instructor": "Rene Caldentey",
    "term": "Spring 2021",
    "hoursPerWeek": 6.9,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.6
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2021",
    "hoursPerWeek": 4.9,
    "clarity": 3.9,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "40000 03",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2021",
    "hoursPerWeek": 4.4,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 3.8
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2021",
    "hoursPerWeek": 4.0,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.9,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2021",
    "hoursPerWeek": 4.6,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2021",
    "hoursPerWeek": 4.9,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.7,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "40108 85",
    "title": "Revenue Management",
    "instructor": "Rene Caldentey",
    "term": "Spring 2022",
    "hoursPerWeek": 6.0,
    "clarity": 3.8,
    "interest": 3.9,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2022",
    "hoursPerWeek": 3.7,
    "clarity": 4.1,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Spring 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Spring 2023",
    "hoursPerWeek": 3.7,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Spring 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Spring 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.2,
    "interest": 3.8,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.6
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2024",
    "hoursPerWeek": 4.0,
    "clarity": 4.3,
    "interest": 3.8,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.4
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "40108 81",
    "title": "Revenue Management",
    "instructor": "Rene Caldentey",
    "term": "Spring 2024",
    "hoursPerWeek": 6.9,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "40110 01",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Spring 2024",
    "hoursPerWeek": 3.3,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "40110 81",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Spring 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.5,
    "interest": 4.1,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2020",
    "hoursPerWeek": 6.4,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2020",
    "hoursPerWeek": 4.9,
    "clarity": 4.9,
    "interest": 5.0,
    "usefulness": 4.9,
    "overall": 4.7,
    "recommendation": 4.9
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2021",
    "hoursPerWeek": 4.4,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2021",
    "hoursPerWeek": 4.4,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2022",
    "hoursPerWeek": 4.0,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2022",
    "hoursPerWeek": 5.3,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2023",
    "hoursPerWeek": 4.9,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2023",
    "hoursPerWeek": 5.7,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Sergio Chayet",
    "term": "Summer 2024",
    "hoursPerWeek": 4.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "40108 01",
    "title": "Revenue Management",
    "instructor": "John Birge",
    "term": "Winter 2021",
    "hoursPerWeek": 5.0,
    "clarity": 3.3,
    "interest": 3.3,
    "usefulness": 3.6,
    "overall": 3.2,
    "recommendation": 3.1
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Winter 2021",
    "hoursPerWeek": 3.9,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Winter 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Winter 2021",
    "hoursPerWeek": 4.2,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Winter 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Nicole Dehoratius",
    "term": "Winter 2021",
    "hoursPerWeek": 4.0,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "40110 01",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.0,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "40110 81",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40108 01",
    "title": "Revenue Management",
    "instructor": "John Birge",
    "term": "Winter 2022",
    "hoursPerWeek": 3.9,
    "clarity": 3.7,
    "interest": 3.5,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.3
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Winter 2022",
    "hoursPerWeek": 4.1,
    "clarity": 4.9,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Winter 2022",
    "hoursPerWeek": 4.0,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "40110 01",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2022",
    "hoursPerWeek": 3.7,
    "clarity": 4.7,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "40110 81",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "40000 03",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Winter 2022",
    "hoursPerWeek": 3.8,
    "clarity": 4.3,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.2
  },
  {
    "id": "40000 04",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Winter 2022",
    "hoursPerWeek": 4.4,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Winter 2022",
    "hoursPerWeek": 4.3,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "40108 85",
    "title": "Revenue Management",
    "instructor": "John Birge",
    "term": "Winter 2023",
    "hoursPerWeek": 4.9,
    "clarity": 3.0,
    "interest": 2.7,
    "usefulness": 3.1,
    "overall": 2.7,
    "recommendation": 2.5
  },
  {
    "id": "40110 01",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 3.8,
    "overall": 3.5,
    "recommendation": 3.6
  },
  {
    "id": "40110 81",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2023",
    "hoursPerWeek": 4.3,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "40110 85",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2023",
    "hoursPerWeek": 4.2,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.7
  },
  {
    "id": "40000 03",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 3.7,
    "interest": 3.8,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 3.4
  },
  {
    "id": "40000 04",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2023",
    "hoursPerWeek": 3.3,
    "clarity": 3.6,
    "interest": 3.5,
    "usefulness": 3.7,
    "overall": 3.2,
    "recommendation": 3.3
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.0,
    "interest": 3.9,
    "usefulness": 3.7,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Winter 2023",
    "hoursPerWeek": 4.3,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Winter 2023",
    "hoursPerWeek": 5.0,
    "clarity": 4.3,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2024",
    "hoursPerWeek": 3.4,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2024",
    "hoursPerWeek": 3.7,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.8,
    "overall": 4.8,
    "recommendation": 4.7
  },
  {
    "id": "40108 01",
    "title": "Revenue Management",
    "instructor": "John Birge",
    "term": "Winter 2024",
    "hoursPerWeek": 4.0,
    "clarity": 3.3,
    "interest": 3.3,
    "usefulness": 3.1,
    "overall": 2.9,
    "recommendation": 2.9
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Levi DeValve",
    "term": "Winter 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.3,
    "interest": 3.9,
    "usefulness": 3.9,
    "overall": 3.5,
    "recommendation": 3.7
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Levi DeValve",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2025",
    "hoursPerWeek": 3.6,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "40000 85",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Linwei Xin",
    "term": "Winter 2025",
    "hoursPerWeek": 4.0,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "40101 01",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Levi DeValve",
    "term": "Winter 2025",
    "hoursPerWeek": 3.9,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "40101 02",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Levi DeValve",
    "term": "Winter 2025",
    "hoursPerWeek": 4.0,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "40101 81",
    "title": "Supply Chain Strategy and Practice",
    "instructor": "Levi DeValve",
    "term": "Winter 2025",
    "hoursPerWeek": 5.1,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "40110 01",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2025",
    "hoursPerWeek": 3.7,
    "clarity": 3.6,
    "interest": 3.5,
    "usefulness": 3.6,
    "overall": 3.2,
    "recommendation": 2.9
  },
  {
    "id": "40110 81",
    "title": "Managing Service Operations",
    "instructor": "Amy Ward",
    "term": "Winter 2025",
    "hoursPerWeek": 4.5,
    "clarity": 3.8,
    "interest": 3.9,
    "usefulness": 3.6,
    "overall": 3.2,
    "recommendation": 3.3
  },
  {
    "id": "40000 01",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2025",
    "hoursPerWeek": 3.8,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "40000 02",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.1,
    "interest": 3.7,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.6
  },
  {
    "id": "40000 03",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Spring 2025",
    "hoursPerWeek": 3.1,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "40000 04",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Ozan Candogan",
    "term": "Spring 2025",
    "hoursPerWeek": 3.9,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.4,
    "recommendation": 3.6
  },
  {
    "id": "40000 81",
    "title": "Operations Management: Business Process Fundamentals",
    "instructor": "Yuan Zhong",
    "term": "Spring 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "40108 85",
    "title": "Revenue Management",
    "instructor": "Rene Caldentey",
    "term": "Spring 2025",
    "hoursPerWeek": 6.6,
    "clarity": 3.9,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.0
  }
];