const courseData = [
  {
    "id": "42201 81",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.2,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42201 85",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.0,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42201 81",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.0,
    "clarity": 4.1,
    "interest": 4.3,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.9
  },
  {
    "id": "42201 85",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.1,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.1,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.7
  },
  {
    "id": "42201 81",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2022",
    "hoursPerWeek": 2.6,
    "clarity": 4.0,
    "interest": 4.4,
    "usefulness": 3.6,
    "overall": 3.5,
    "recommendation": 3.9
  },
  {
    "id": "42201 85",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.5,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.5,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "42201 81",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.3,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 3.8,
    "overall": 3.3,
    "recommendation": 3.8
  },
  {
    "id": "42201 85",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.7,
    "clarity": 4.2,
    "interest": 4.6,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "42201 81",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2024",
    "hoursPerWeek": 2.7,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 3.9,
    "overall": 3.8,
    "recommendation": 4.1
  },
  {
    "id": "42201 85",
    "title": "The Legal Infrastructure of Business",
    "instructor": "Randal Picker",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.3,
    "interest": 4.6,
    "usefulness": 4.0,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Spring 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.1,
    "interest": 3.9,
    "usefulness": 3.9,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "33305 01",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2021",
    "hoursPerWeek": 3.6,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "33305 81",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2021",
    "hoursPerWeek": 4.1,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "33305 85",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "33305 01",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2022",
    "hoursPerWeek": 4.7,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "33305 81",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2022",
    "hoursPerWeek": 5.8,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "33305 85",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2022",
    "hoursPerWeek": 4.8,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "38119 01",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Spring 2022",
    "hoursPerWeek": 3.7,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "38119 02",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Spring 2022",
    "hoursPerWeek": 3.5,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.2,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "38119 81",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Spring 2022",
    "hoursPerWeek": 3.6,
    "clarity": 4.9,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "33305 01",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2023",
    "hoursPerWeek": 3.5,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "33305 81",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2023",
    "hoursPerWeek": 4.5,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "33305 85",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2023",
    "hoursPerWeek": 5.0,
    "clarity": 4.7,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "33250 01",
    "title": "Perspectives on Capitalism",
    "instructor": "Robert H Gertner",
    "term": "Spring 2024",
    "hoursPerWeek": 6.5,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "33250 81",
    "title": "Perspectives on Capitalism",
    "instructor": "Robert H Gertner",
    "term": "Spring 2024",
    "hoursPerWeek": 8.5,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "33305 01",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "33305 02",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "33305 81",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "37212 01",
    "title": "Business with Purpose",
    "instructor": "Abigail Sussman",
    "term": "Spring 2024",
    "hoursPerWeek": 3.2,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "37212 81",
    "title": "Business with Purpose",
    "instructor": "Abigail Sussman",
    "term": "Spring 2024",
    "hoursPerWeek": 2.7,
    "clarity": 4.3,
    "interest": 3.7,
    "usefulness": 3.3,
    "overall": 3.2,
    "recommendation": 3.1
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2021",
    "hoursPerWeek": 4.5,
    "clarity": 4.2,
    "interest": 4.4,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "33471 81",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2021",
    "hoursPerWeek": 4.3,
    "clarity": 4.1,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "33471 85",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2021",
    "hoursPerWeek": 3.6,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "38119 01",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2021",
    "hoursPerWeek": 4.7,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "38119 81",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2021",
    "hoursPerWeek": 5.2,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "38119 85",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2021",
    "hoursPerWeek": 7.6,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Robert H Gertner",
    "term": "Winter 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.2,
    "interest": 3.7,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "34117 81",
    "title": "Social Entrepreneurship and Innovation",
    "instructor": "Robert H Gertner",
    "term": "Winter 2021",
    "hoursPerWeek": 4.3,
    "clarity": 4.6,
    "interest": 4.1,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.3
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Winter 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.2,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.2
  },
  {
    "id": "33471 81",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2022",
    "hoursPerWeek": 5.4,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "33471 85",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2022",
    "hoursPerWeek": 4.8,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Robert H Gertner",
    "term": "Winter 2022",
    "hoursPerWeek": 4.1,
    "clarity": 3.1,
    "interest": 2.8,
    "usefulness": 3.4,
    "overall": 3.1,
    "recommendation": 3.1
  },
  {
    "id": "34117 81",
    "title": "Social Entrepreneurship and Innovation",
    "instructor": "Robert H Gertner",
    "term": "Winter 2022",
    "hoursPerWeek": 4.4,
    "clarity": 3.5,
    "interest": 2.9,
    "usefulness": 3.3,
    "overall": 2.9,
    "recommendation": 2.9
  },
  {
    "id": "34117 81",
    "title": "Social Entrepreneurship and Innovation",
    "instructor": "Christina Hachikian",
    "term": "Winter 2022",
    "hoursPerWeek": 4.4,
    "clarity": 4.1,
    "interest": 3.8,
    "usefulness": 3.3,
    "overall": 2.9,
    "recommendation": 2.9
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Winter 2022",
    "hoursPerWeek": 4.1,
    "clarity": 3.7,
    "interest": 3.8,
    "usefulness": 3.4,
    "overall": 3.1,
    "recommendation": 3.1
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "33471 02",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2023",
    "hoursPerWeek": 4.0,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "33471 81",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "38119 01",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2023",
    "hoursPerWeek": 4.2,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "38119 02",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2023",
    "hoursPerWeek": 3.3,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "38119 85",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2023",
    "hoursPerWeek": 3.8,
    "clarity": 4.8,
    "interest": 5.0,
    "usefulness": 4.8,
    "overall": 4.9,
    "recommendation": 4.9
  },
  {
    "id": "34117 01",
    "title": "Social Entrepreneurship and Innovation",
    "instructor": "Robert H Gertner",
    "term": "Winter 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.2,
    "interest": 3.8,
    "usefulness": 4.0,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2024",
    "hoursPerWeek": 5.4,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.0
  },
  {
    "id": "33471 02",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2024",
    "hoursPerWeek": 3.2,
    "clarity": 3.9,
    "interest": 4.3,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 4.2
  },
  {
    "id": "33471 81",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2024",
    "hoursPerWeek": 4.9,
    "clarity": 4.4,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.3
  },
  {
    "id": "38119 01",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 3.8,
    "overall": 3.6,
    "recommendation": 3.6
  },
  {
    "id": "38119 02",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.6,
    "interest": 4.4,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "38119 81",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2024",
    "hoursPerWeek": 3.9,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "34117 01",
    "title": "Social Entrepreneurship and Innovation",
    "instructor": "Robert H Gertner",
    "term": "Winter 2024",
    "hoursPerWeek": 4.8,
    "clarity": 4.2,
    "interest": 3.6,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 3.8
  },
  {
    "id": "33471 01",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2025",
    "hoursPerWeek": 4.1,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "33471 02",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2025",
    "hoursPerWeek": 4.6,
    "clarity": 4.1,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "33471 03",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "33471 85",
    "title": "Business, Politics, and Ethics",
    "instructor": "Brian Barry",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "34113 01",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Winter 2025",
    "hoursPerWeek": 4.0,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "34113 81",
    "title": "Impact Investing",
    "instructor": "Priya Khetarpal",
    "term": "Winter 2025",
    "hoursPerWeek": 4.7,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 3.9,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "37212 01",
    "title": "Business with Purpose",
    "instructor": "Abigail Sussman",
    "term": "Winter 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.0,
    "interest": 3.6,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.6
  },
  {
    "id": "37212 81",
    "title": "Business with Purpose",
    "instructor": "Abigail Sussman",
    "term": "Winter 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.5
  },
  {
    "id": "38119 01",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2025",
    "hoursPerWeek": 3.8,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "38119 02",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2025",
    "hoursPerWeek": 3.9,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "38119 81",
    "title": "Designing a Good Life",
    "instructor": "Nicholas Epley",
    "term": "Winter 2025",
    "hoursPerWeek": 3.4,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "33250 01",
    "title": "Perspectives on Capitalism",
    "instructor": "Robert H Gertner",
    "term": "Spring 2025",
    "hoursPerWeek": 4.5,
    "clarity": 4.1,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "33250 81",
    "title": "Perspectives on Capitalism",
    "instructor": "Robert H Gertner",
    "term": "Spring 2025",
    "hoursPerWeek": 4.3,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "33305 01",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2025",
    "hoursPerWeek": 3.8,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.5
  },
  {
    "id": "33305 02",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2025",
    "hoursPerWeek": 4.7,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "33305 85",
    "title": "The Firm and the Non-Market Environment",
    "instructor": "Marianne Bertrand",
    "term": "Spring 2025",
    "hoursPerWeek": 5.5,
    "clarity": 4.6,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  }
];