const courseData = [
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.8,
    "clarity": 4.1,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "42001 05",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2020",
    "hoursPerWeek": 5.2,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.5,
    "clarity": 4.2,
    "interest": 3.7,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "39101 81",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2020",
    "hoursPerWeek": 5.1,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Ram Shivakumar",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.9,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.3,
    "clarity": 4.0,
    "interest": 4.0,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.3,
    "clarity": 4.2,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.4,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2020",
    "hoursPerWeek": 4.1,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2020",
    "hoursPerWeek": 3.8,
    "clarity": 4.6,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.7,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.8
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.7,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.7,
    "recommendation": 4.1
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.7
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.0,
    "interest": 3.5,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.6
  },
  {
    "id": "39101 85",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2021",
    "hoursPerWeek": 5.0,
    "clarity": 4.0,
    "interest": 3.8,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 3.8
  },
  {
    "id": "42001 05",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.2,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.6,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2021",
    "hoursPerWeek": 3.9,
    "clarity": 4.5,
    "interest": 4.8,
    "usefulness": 4.3,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2021",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.6,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "42001 05",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.6,
    "clarity": 3.6,
    "interest": 3.3,
    "usefulness": 3.8,
    "overall": 3.5,
    "recommendation": 3.3
  },
  {
    "id": "42116 01",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.9,
    "clarity": 4.4,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "42116 81",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.3,
    "interest": 4.7,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "39101 81",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.9,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.6,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Chad Syverson",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2022",
    "hoursPerWeek": 3.9,
    "clarity": 4.6,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.2,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 4.9,
    "overall": 4.8,
    "recommendation": 4.9
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2022",
    "hoursPerWeek": 4.1,
    "clarity": 4.7,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.0
  },
  {
    "id": "39101 81",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.2,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.7,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.8
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.6,
    "clarity": 4.8,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.6
  },
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.3,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "42001 05",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.3,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.3,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2023",
    "hoursPerWeek": 3.9,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.5,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Autumn 2023",
    "hoursPerWeek": 4.0,
    "clarity": 4.3,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Autumn 2023",
    "hoursPerWeek": 5.1,
    "clarity": 4.1,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.1,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "39101 81",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.1,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.5,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.7,
    "interest": 4.8,
    "usefulness": 4.6,
    "overall": 4.3,
    "recommendation": 4.7
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.5,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.8
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Autumn 2024",
    "hoursPerWeek": 6.0,
    "clarity": 4.0,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.0,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Thomas Wollmann",
    "term": "Autumn 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.8,
    "interest": 5.0,
    "usefulness": 4.7,
    "overall": 4.5,
    "recommendation": 4.7
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.2,
    "clarity": 4.0,
    "interest": 4.2,
    "usefulness": 4.2,
    "overall": 3.5,
    "recommendation": 3.5
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.5,
    "clarity": 4.4,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 3.9
  },
  {
    "id": "42116 01",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.3,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "42116 81",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Autumn 2024",
    "hoursPerWeek": 4.7,
    "clarity": 3.9,
    "interest": 4.3,
    "usefulness": 3.9,
    "overall": 3.4,
    "recommendation": 3.7
  },
  {
    "id": "42116 01",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2021",
    "hoursPerWeek": 4.2,
    "clarity": 3.8,
    "interest": 4.0,
    "usefulness": 3.8,
    "overall": 3.7,
    "recommendation": 3.5
  },
  {
    "id": "42116 81",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2021",
    "hoursPerWeek": 5.1,
    "clarity": 3.9,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "42116 85",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2021",
    "hoursPerWeek": 10.9,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Spring 2021",
    "hoursPerWeek": 3.3,
    "clarity": 3.8,
    "interest": 4.2,
    "usefulness": 3.9,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "39001 01",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2021",
    "hoursPerWeek": 3.4,
    "clarity": 4.2,
    "interest": 3.7,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "39001 02",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2021",
    "hoursPerWeek": 4.2,
    "clarity": 4.2,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "39001 81",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2021",
    "hoursPerWeek": 3.8,
    "clarity": 4.3,
    "interest": 3.9,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Yoad Shefi",
    "term": "Spring 2021",
    "hoursPerWeek": 3.6,
    "clarity": 3.2,
    "interest": 2.8,
    "usefulness": 3.3,
    "overall": 3.0,
    "recommendation": 2.9
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Yoad Shefi",
    "term": "Spring 2021",
    "hoursPerWeek": 4.3,
    "clarity": 3.6,
    "interest": 3.5,
    "usefulness": 3.8,
    "overall": 3.4,
    "recommendation": 3.5
  },
  {
    "id": "42116 01",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2022",
    "hoursPerWeek": 4.9,
    "clarity": 4.5,
    "interest": 4.6,
    "usefulness": 4.4,
    "overall": 4.4,
    "recommendation": 4.4
  },
  {
    "id": "42116 02",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2022",
    "hoursPerWeek": 3.7,
    "clarity": 4.2,
    "interest": 4.7,
    "usefulness": 4.1,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "42116 81",
    "title": "Game Theory",
    "instructor": "Emir Kamenica",
    "term": "Spring 2022",
    "hoursPerWeek": 4.2,
    "clarity": 4.4,
    "interest": 4.8,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.4
  },
  {
    "id": "39101 81",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.6
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2022",
    "hoursPerWeek": 3.4,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.0
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2022",
    "hoursPerWeek": 4.3,
    "clarity": 3.9,
    "interest": 3.6,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.7
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Ryan Mcdevitt",
    "term": "Spring 2022",
    "hoursPerWeek": 4.6,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.5,
    "recommendation": 4.5
  },
  {
    "id": "42001 04",
    "title": "Competitive Strategy",
    "instructor": "Ryan Mcdevitt",
    "term": "Spring 2022",
    "hoursPerWeek": 3.6,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.2
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Ryan Mcdevitt",
    "term": "Spring 2022",
    "hoursPerWeek": 3.4,
    "clarity": 4.8,
    "interest": 4.7,
    "usefulness": 4.7,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "39001 01",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2022",
    "hoursPerWeek": 3.2,
    "clarity": 4.1,
    "interest": 3.8,
    "usefulness": 3.9,
    "overall": 3.6,
    "recommendation": 3.6
  },
  {
    "id": "39001 02",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2022",
    "hoursPerWeek": 4.5,
    "clarity": 4.6,
    "interest": 3.9,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "39001 85",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Amanda Sharkey",
    "term": "Spring 2022",
    "hoursPerWeek": 3.8,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.1,
    "overall": 4.1,
    "recommendation": 4.0
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Luis Garicano Gabilondo",
    "term": "Spring 2023",
    "hoursPerWeek": 3.0,
    "clarity": 4.0,
    "interest": 5.0,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2023",
    "hoursPerWeek": 4.4,
    "clarity": 4.0,
    "interest": 3.5,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "39101 85",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2023",
    "hoursPerWeek": 5.1,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.1
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2023",
    "hoursPerWeek": 3.9,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.1,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2023",
    "hoursPerWeek": 3.3,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "39001 01",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Ningzi Li",
    "term": "Spring 2023",
    "hoursPerWeek": 3.2,
    "clarity": 4.0,
    "interest": 3.8,
    "usefulness": 3.4,
    "overall": 3.3,
    "recommendation": 3.2
  },
  {
    "id": "39001 02",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Ningzi Li",
    "term": "Spring 2023",
    "hoursPerWeek": 2.9,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 3.3,
    "overall": 3.2,
    "recommendation": 3.2
  },
  {
    "id": "39001 81",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Ningzi Li",
    "term": "Spring 2024",
    "hoursPerWeek": 3.7,
    "clarity": 3.8,
    "interest": 3.6,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.6
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2024",
    "hoursPerWeek": 4.1,
    "clarity": 3.8,
    "interest": 3.4,
    "usefulness": 4.1,
    "overall": 3.5,
    "recommendation": 3.6
  },
  {
    "id": "39101 85",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2024",
    "hoursPerWeek": 4.0,
    "clarity": 4.3,
    "interest": 4.0,
    "usefulness": 4.6,
    "overall": 4.1,
    "recommendation": 3.9
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Spring 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.1,
    "interest": 3.7,
    "usefulness": 3.7,
    "overall": 3.2,
    "recommendation": 3.4
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Spring 2024",
    "hoursPerWeek": 5.0,
    "clarity": 4.5,
    "interest": 4.7,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.2
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Thomas Covert",
    "term": "Spring 2024",
    "hoursPerWeek": 5.1,
    "clarity": 4.4,
    "interest": 4.2,
    "usefulness": 4.3,
    "overall": 4.2,
    "recommendation": 4.0
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Summer 2020",
    "hoursPerWeek": 3.4,
    "clarity": 3.7,
    "interest": 4.1,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Summer 2020",
    "hoursPerWeek": 3.9,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.5,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Summer 2021",
    "hoursPerWeek": 3.2,
    "clarity": 4.1,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.0,
    "recommendation": 4.3
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Summer 2021",
    "hoursPerWeek": 2.9,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 4.0
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Summer 2022",
    "hoursPerWeek": 3.1,
    "clarity": 3.8,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Summer 2023",
    "hoursPerWeek": 3.9,
    "clarity": 4.0,
    "interest": 3.8,
    "usefulness": 3.6,
    "overall": 3.4,
    "recommendation": 3.6
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2021",
    "hoursPerWeek": 3.5,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.7,
    "recommendation": 4.0
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2021",
    "hoursPerWeek": 3.9,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "39101 85",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Winter 2021",
    "hoursPerWeek": 5.3,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.7,
    "overall": 4.3,
    "recommendation": 4.4
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Winter 2021",
    "hoursPerWeek": 4.0,
    "clarity": 3.9,
    "interest": 3.8,
    "usefulness": 3.8,
    "overall": 3.6,
    "recommendation": 3.7
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Winter 2021",
    "hoursPerWeek": 4.1,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "42001 82",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Winter 2021",
    "hoursPerWeek": 5.7,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.1,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2022",
    "hoursPerWeek": 3.8,
    "clarity": 4.6,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 4.1,
    "recommendation": 4.2
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2022",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.3,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.2
  },
  {
    "id": "42715 01",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2022",
    "hoursPerWeek": 3.4,
    "clarity": 4.7,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.9
  },
  {
    "id": "39001 01",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Ningzi Li",
    "term": "Winter 2022",
    "hoursPerWeek": 3.4,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 3.7,
    "overall": 3.4,
    "recommendation": 3.7
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Ram Shivakumar",
    "term": "Winter 2022",
    "hoursPerWeek": 3.9,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.6,
    "overall": 4.6,
    "recommendation": 4.7
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2023",
    "hoursPerWeek": 3.9,
    "clarity": 4.1,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.5,
    "recommendation": 3.9
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2023",
    "hoursPerWeek": 3.8,
    "clarity": 3.9,
    "interest": 3.5,
    "usefulness": 3.7,
    "overall": 3.3,
    "recommendation": 3.3
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2023",
    "hoursPerWeek": 4.1,
    "clarity": 4.4,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.1,
    "recommendation": 4.3
  },
  {
    "id": "42715 85",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2023",
    "hoursPerWeek": 4.7,
    "clarity": 4.5,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Sonia Marciano",
    "term": "Winter 2023",
    "hoursPerWeek": 4.4,
    "clarity": 3.3,
    "interest": 3.5,
    "usefulness": 3.6,
    "overall": 3.2,
    "recommendation": 3.2
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2024",
    "hoursPerWeek": 4.7,
    "clarity": 4.2,
    "interest": 4.0,
    "usefulness": 4.0,
    "overall": 3.8,
    "recommendation": 3.9
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Eric Budish",
    "term": "Winter 2024",
    "hoursPerWeek": 4.4,
    "clarity": 4.5,
    "interest": 4.4,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.6
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Milena Almagro Garcia",
    "term": "Winter 2024",
    "hoursPerWeek": 4.8,
    "clarity": 3.7,
    "interest": 3.9,
    "usefulness": 3.9,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Milena Almagro Garcia",
    "term": "Winter 2024",
    "hoursPerWeek": 4.6,
    "clarity": 4.3,
    "interest": 4.4,
    "usefulness": 4.3,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "42715 01",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2024",
    "hoursPerWeek": 3.6,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.5,
    "overall": 4.3,
    "recommendation": 4.5
  },
  {
    "id": "42715 81",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2024",
    "hoursPerWeek": 3.8,
    "clarity": 4.4,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 4.0,
    "recommendation": 4.1
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Anders Humlum",
    "term": "Winter 2025",
    "hoursPerWeek": 3.4,
    "clarity": 4.4,
    "interest": 4.3,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Anders Humlum",
    "term": "Winter 2025",
    "hoursPerWeek": 2.6,
    "clarity": 4.7,
    "interest": 4.6,
    "usefulness": 4.5,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "42001 03",
    "title": "Competitive Strategy",
    "instructor": "Milena Almagro Garcia",
    "term": "Winter 2025",
    "hoursPerWeek": 2.7,
    "clarity": 5.0,
    "interest": 5.0,
    "usefulness": 5.0,
    "overall": 4.8,
    "recommendation": 5.0
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Milena Almagro Garcia",
    "term": "Winter 2025",
    "hoursPerWeek": 3.4,
    "clarity": 4.3,
    "interest": 4.3,
    "usefulness": 4.2,
    "overall": 3.9,
    "recommendation": 4.1
  },
  {
    "id": "42715 01",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "42800 92",
    "title": "Competitive Strategy",
    "instructor": "Luis Garicano Gabilondo",
    "term": "Winter 2025",
    "hoursPerWeek": 8.5,
    "clarity": 3.9,
    "interest": 4.4,
    "usefulness": 4.4,
    "overall": 4.2,
    "recommendation": 4.3
  },
  {
    "id": "42800 93",
    "title": "Competitive Strategy",
    "instructor": "Luis Garicano Gabilondo",
    "term": "Winter 2025",
    "hoursPerWeek": 11.3,
    "clarity": 4.4,
    "interest": 4.7,
    "usefulness": 4.6,
    "overall": 4.5,
    "recommendation": 4.6
  },
  {
    "id": "42715 01",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.8,
    "interest": 4.9,
    "usefulness": 4.8,
    "overall": 4.7,
    "recommendation": 4.8
  },
  {
    "id": "42715 85",
    "title": "Strategy Simulation: Creating Value in Complex and Ambiguous Settings",
    "instructor": "Kathleen Fitzgerald",
    "term": "Winter 2025",
    "hoursPerWeek": 4.4,
    "clarity": 4.6,
    "interest": 4.6,
    "usefulness": 4.6,
    "overall": 4.4,
    "recommendation": 4.5
  },
  {
    "id": "39001 81",
    "title": "Strategy and Structure: Markets and Organizations",
    "instructor": "Ningzi Li",
    "term": "Spring 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.1,
    "interest": 3.4,
    "usefulness": 4.0,
    "overall": 3.6,
    "recommendation": 3.5
  },
  {
    "id": "39101 01",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2025",
    "hoursPerWeek": 4.9,
    "clarity": 3.9,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 4.0,
    "recommendation": 3.9
  },
  {
    "id": "39101 85",
    "title": "Technology Strategy",
    "instructor": "Marc James Knez",
    "term": "Spring 2025",
    "hoursPerWeek": 4.2,
    "clarity": 4.4,
    "interest": 4.6,
    "usefulness": 4.8,
    "overall": 4.6,
    "recommendation": 4.4
  },
  {
    "id": "42001 01",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2025",
    "hoursPerWeek": 3.4,
    "clarity": 4.2,
    "interest": 4.2,
    "usefulness": 4.0,
    "overall": 3.7,
    "recommendation": 3.8
  },
  {
    "id": "42001 02",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2025",
    "hoursPerWeek": 3.2,
    "clarity": 4.0,
    "interest": 3.6,
    "usefulness": 3.9,
    "overall": 3.2,
    "recommendation": 3.4
  },
  {
    "id": "42001 81",
    "title": "Competitive Strategy",
    "instructor": "Jacob Leshno",
    "term": "Spring 2025",
    "hoursPerWeek": 3.5,
    "clarity": 4.2,
    "interest": 4.1,
    "usefulness": 4.1,
    "overall": 3.8,
    "recommendation": 3.8
  },
  {
    "id": "42001 85",
    "title": "Competitive Strategy",
    "instructor": "Ram Shivakumar",
    "term": "Spring 2025",
    "hoursPerWeek": 3.7,
    "clarity": 4.3,
    "interest": 4.5,
    "usefulness": 4.2,
    "overall": 3.8,
    "recommendation": 4.1
  }
];